# Generated by Django 2.1.7 on 2019-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digifest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('cpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
